//USER AUTHENTICATION CONSTANTS
export const LOGGING_IN_USER = "auth:LOGGING_IN_USER";
export const LOGGED_IN_USER = "auth:LOGGED_IN_USER";
export const ERROR_LOGGING_IN_USER = "auth:ERROR_LOGGING_IN_USER";
export const REQUEST_ERROR = "request:REQUEST_ERROR";

//CREATE PROJECT CONSTANTS
export const CREATING_PROJECT = "project:CREATING_PROJECT";
export const CREATED_PROJECT = "project:CREATED_PROJECT";
export const ERROR_CREATING_PROJECT = "project:ERROR_CREATING_PROJECT";

//LOAD PROJECTS CONSTANTS
export const LOADING_PROJECT = "project:LOADING_PROJECT";
export const LOADED_PROJECT = "project:LOADED_PROJECT";
export const ERROR_LOADING_PROJECT = "project:ERROR_LOADING_PROJECT";

//LOAD LOCATIONS CONSTANTS
export const LOADING_LOCATIONS = "project:LOADING_LOCATIONS";
export const LOADED_LOCATIONS = "project:LOADED_LOCATIONS";
export const ERROR_LOADING_LOCATIONS = "project:ERROR_LOADING_LOCATIONS";

//CLEAR LOGIN SUCCESS CONSTANT
export const CLEAR_LOGIN_SUCCESS = "clear:CLEAR_LOGIN_SUCCESS";
